### ISSUE TITLE
Make Lutris Addon easier to install

### ISSUE THREAD

**Issue by lefty420** [RobLoach/lutris-kodi-addon#13]
Dude this addon is amazing thank you so much for your efforts!! Have you thought about setting up a repo or submitting the addon to the official kodi team?

**Comment by RobLoach** [comment]
Thanks! Thought about submitting it to Kodi's official repository, but the requirements are pretty tight.

1. You need to be running Linux (not arm, Windows or Mac)
2. You need to install/set up Lutris yourself

Considering that, I'd imagine there would just be a bunch of support requests asking for help on setting it up on a Mac or an Android device :stuck_out_tongue:

Lutris is also not in its 1.x branch yet either, which means that the API or requirements to run it are also not yet stable. So considering all the above, I'd hold off on submitting to the official repo. I did submit it on SuperRepo though!
https://superrepo.org/kodi/addon/script.lutris/

**Comment by RobLoach** [comment]
Do you know another good Kodi repo out there we could use?

**Comment by solbero** [comment]
@RobLoach You could roll your own addon-repo from a Github repository. An explanation is on the [official Kodi wiki](http://kodi.wiki/view/how-to:create_a_repository_for_add-ons).

To be honest, hosting the add-on on SuperRepo is not optimal. SuperRepo doesn’t have strict submission guidelines, and therefore it also attracts a lot of illegal/grey-area addons. From a user perspective, having SuperRepo enabled and submitting a log to the Kodi forums will result in no support until the repository is disabled. The repository is [listed on the forum blacklist](http://kodi.wiki/view/Official:Forum_rules/Banned_add-ons).

This is why I, in my guide, explain how to do a manual install of the Kodi Lutris add-on. It is not optimal, but it will not cause support issues down the road.

**Comment by solbero** [comment]
If you don't mind, @RobLoach, I would like to take a stab at setting up a GitHub repo for the add-on. This would be a nice supplement to the SuperRepo repo. What are your thoughts?

**Comment by RobLoach** [comment]
@solbero Definitely would be helpful! Then people could just add the repo directly, rather than going through a third-party one.

**Comment by solbero** [comment]
I have created a repo for the add-on: https://github.com/solbero/repository.solbero. I’ll test it tonight.

**Comment by solbero** [comment]
The repository works well. I will update the `README.md` with the new installation instructions.

**Comment by solbero** [comment]
With the new README instructions and the repository I set up I’m going to say that this issue is solved.
