### ISSUE TITLE
Launching games brings up Lutris in Kodi

### ISSUE THREAD

**Issue by solbero** [RobLoach/lutris-kodi-addon#14]
I have used your add-on for a while, but lately it has started to bring up Lutris in Kodi when I launch a game. In Lutris a dialogue is displayed which asks me if i want to launch the game or install it. This only happens when I launch a game from the add-on, but not if I bring up Lutris and then launch a game from there. I have updated the add-on to 1.1.1.

This is not ideal for me, since I’m using a controller and therefore have to get a keyboard and mouse to close Lutris.

I’m on Kodi v17.3 using Ubuntu 16.04.

**Comment by strycore** [comment]
@solbero are you sure the addon is up to date? I checked the latest revision and the addon launches games with lutris:rungame/[gameid] which is the correct way to do it and shouldn't bring up this dialog.

**Comment by strycore** [comment]
@RobLoach btw, you might want to use `rungameid` instead of `rungame` since several games can have the same slug.

**Comment by solbero** [comment]
Hare are the lines from ` default.py` I have installed. Everything looks fine there.

```python
# Launch
elif mode[0] == 'folder':
    lutris = settings.getSetting('lutris_executable')
    slug = args['slug'][0]
    cmd = lutris
    if slug != 'lutris':
        cmd = cmd + ' lutris:rungame/' + slug
    os.system(cmd)
```

I’ll try a clean reinstall and see if that helps

**Comment by RobLoach** [comment]
Confirmed....

1. Open up your terminal
2. Run `lutris lutris:rungame/tuxracer`
3. Lutris window pops up and runs the game
4. When you quit the game, Lutris stays open.

Openned up https://github.com/lutris/lutris/issues/578 to have a look at this.

> btw, you might want to use rungameid instead of rungame since several games can have the same slug.

Good call! I'll make an issue for it.

**Comment by arustler** [comment]
same with the snes runner

**Comment by solbero** [comment]
Lutris v0.4.15 has now been released. As of this version the Lutris GUI is not displayed when a game is launched by the Lutris Kodi Addon.
