### ISSUE TITLE
Add option to change icon type in add-on settings

### ISSUE THREAD

**Issue by solbero** [RobLoach/lutris-kodi-addon#16]
Would it be possible to expose an option in the add-on’s settings to change the game icons from banner to square icons? Bothe icon sets are used by the Lutris client.

Some kodi skins (such as Pellucid, probably others as well) display the game icons in a square in the add-on. To fit this square the banner icons are compressed along the x-axis. However, the square icons from Lutris would fit beautifully. Also, I imagine the square icons would fit better in those skins where you can display the games in list view.

**Comment by RobLoach** [comment]
The setting of the icon or the banner is over at https://github.com/RobLoach/lutris-kodi-addon/blob/master/default.py#L77-L85

Feel free to change it up and submit what you think would be good. I don't think this needs to be an option, just make the change and push it up in the PR! :wink:

**Comment by solbero** [comment]
Thanks for pointing me in the right direction. I did some playing around with using `gameThumb` in `default.py` for the thumb view in Kodi. The conclusion is that it looks even worse than the compressed banners. The icons used by Lutris are 32x32 px, therefore are too small to be used on a 10-feet interface.

You can close this issue for now. I could see a point in the future where hi-res square icons could be included with Lutris (might be a possibility with 4k monitors and such becoming more popular), and I can re-open the issue then and submit a PR.
