### ISSUE TITLE
Check if Lutris is installed on first run

### ISSUE THREAD

**Issue by solbero** [RobLoach/lutris-kodi-addon#19]
This is just a thought. On first run, the add-on could check if Lutris is installed in PATH using `distutils.spawn.find_executable`. If it finds it, it could paste the resulting path to settings.xml.

If it doesn’t find it, a dialog box could pop open with some information on where to find Lutris and install it.

**Comment by solbero** [comment]
If no Lutris executable is found, the add-on should also gracefully exit when the information dialog is closed without displaying an empty folder listing the user then has to exit.

**Comment by RobLoach** [comment]
That's a great idea, and would really help on configuration and setup.

The dialog could look similar to the existing one:
https://github.com/RobLoach/lutris-kodi-addon/blob/master/default.py#L46-L55

**Comment by solbero** [comment]
I’ll make a proposal and submit it as a PR. My Python is not the best, so if you could review the PR and make suggestions, I’ll incorporate them.

What I’m thinking about is:
1. Make a test if Lutris is installed with `distutils.spawn.find_executable`.
   * If it is not installed, promt the user.
2. It it is installed, get the path from `distutils.spawn.find_executable`. The add-on never pulls the path from the settings.
3. Make a boolean in the settings such as “Use custom path to executable". If toggled, a grey-outed option where the user can specify the path is made available.
4. Make a test in for step 2. If the the boolean is true, never perform step 1 and 2, and fetch the path from the settings. If set to False, use path from `distutils.spawn.find_executable`.

**Comment by solbero** [comment]
I also noticed that the test in https://github.com/RobLoach/lutris-kodi-addon/blob/master/default.py#L46-L55 has an edge case. If the user has Lutris installed, but has not added any games, the add-on will prompt the user to install Lutris.

I think a better idea is to check for the actual executable in PATH. What do you think?

**Comment by solbero** [comment]
I have added a PR with the proposed changes: https://github.com/RobLoach/lutris-kodi-addon/pull/20

**Comment by solbero** [comment]
I'm going to close this as the feature is now implemented.

**Comment by RobLoach** [comment]
Nice one! Love this new addition :+1:
