### ISSUE TITLE
Lutris gui loads 

### ISSUE THREAD

**Issue by lefty420** [RobLoach/lutris-kodi-addon#25]
Hey guys awesome work with the addon.  I don't know when it happened but now lutris gui loads after I launch a game and doesn't close after exiting the game. Is the common?

**Comment by RobLoach** [comment]
Lutris issue is over at https://github.com/lutris/lutris/issues/578

**Comment by solbero** [comment]
Duplicate of https://github.com/RobLoach/lutris-kodi-addon/issues/14.

**Comment by RobLoach** [comment]
@hzeroo has been doing an awesome job cleaning this up in Lutris upstream :+1:
