### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by solbero** [RobLoach/lutris-kodi-addon#26]
Could you make a new release for the add-on, @RobLoach? There are several new features which I would like to pull into the add-on Kodi repository, but I cannot pull then before a new release is made.

**Comment by solbero** [comment]
Would you mind if I made a release to 1.2.0?

**Comment by RobLoach** [comment]
@solbero Sounds like a good idea! A few things that are g2g. :+1:

**Comment by solbero** [comment]
I have made a release to [1.2.1](https://github.com/RobLoach/lutris-kodi-addon/releases/tag/1.2.1). I have also updated [repository.solbero](https://github.com/solbero/repository.solbero) with the new release.
