### ISSUE TITLE
Unable to run, incorrect directory

### ISSUE THREAD

**Issue by stooj** [RobLoach/lutris-kodi-addon#27]
I installed the lutris kodi addon using solbero's repository, but the plugin doesn't run.

```
21:56:06.125 T:140063799224064   ERROR: GetDirectory - Error getting
21:56:06.220 T:140063170094848   ERROR: Previous line repeats 2 times.
21:56:06.220 T:140063170094848   ERROR: ExecuteAsync - Not executing non-existing script /home/htpc/.kodi/addons/script.lutris/default.py
21:56:06.220 T:140063170094848   ERROR: Unable to run plugin Lutris
21:56:06.220 T:140064920709184   ERROR: GetDirectory - Error getting plugin://script.lutris/
21:56:06.220 T:140064920709184   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.lutris/) failed
```

Looking at the directory, it seems like kodi is looking in the `script.lutris` directory, but the actual script is nested in `script.lutris/script.lutris` directory. 

```
[htpc@ellen addons]$ pwd
/home/htpc/.kodi/addons
[htpc@ellen addons]$ tree script.lutris/
script.lutris/
├── addon.xml
├── changelog-1.1.1.txt
├── changelog-1.2.0.txt
├── changelog-1.2.1.txt
├── fanart.jpg
├── icon.png
├── LICENSE.txt
├── script.lutris
│   ├── addon.xml
│   ├── changelog.txt
│   ├── default.py
│   ├── fanart.jpg
│   ├── icon.png
│   ├── LICENSE.txt
│   ├── README.md
│   └── resources
│       ├── language
│       │   └── English
│       │       └── strings.xml
│       ├── media
│       │   └── screenshot.jpg
│       └── settings.xml
├── script.lutris-1.1.1.zip.md5
├── script.lutris-1.2.0.zip.md5
└── script.lutris-1.2.1.zip.md5
```
5 directories, 20 files

**Comment by RobLoach** [comment]
How did you install this? The repo?

**Comment by stooj** [comment]
Installed using the recommended steps

```
Make sure that Unknown Sources is enabled in Settings → System → Add-ons

Install solbero's Kodi add-on repository

Visit Home → Settings → Add-ons → Install from repository → solbero’s Kodi add-on repository → Program Add-ons → Lutris → Install
```

**Comment by RobLoach** [comment]
@solbero Looks like the zips are embedded? Know what's up?

@stooj As an alternative, you could just install manually for now.

**Comment by stooj** [comment]
Thanks; I'll try a reinstall tonight and then do a manual one if it fails again.

**Comment by solbero** [comment]
I’m looking in to it now. I’ll see if I can create a fix within a few hours.

**Comment by solbero** [comment]
Everything should now be in order. Tru installing the latest (v1.0.1) repository zip-file.

**Comment by stooj** [comment]
Hi - sorry it took so long for me to try this again.

I removed the old repo and plugin, rebooted, then downloaded and installed from the link above.

Still hitting the same issue though; same errors in the log.

**Comment by solbero** [comment]
Did you manage to solve your issue? If not, make sure that you have uninstalled the Lutris Kodi Addon and solbero's Addon Repository in Kodi.

Also, navigate to ~/.kodi/addons/packages/ on your HTPC. In the packages folder, locate the .zip files for both the addon and the repository and delete them. Then install solbero's repository from a new zip file. Make sure you install from the latest version; it should be v1.0.1.

**Comment by solbero** [comment]
Issue seems solved.
