### ISSUE TITLE
Display Run Notification

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/lutris-kodi-addon#30]
When running a game, display a notification to let the user to know to wait...

```
Running %GameName
Please wait...
```

Or something like that.

**Comment by solbero** [comment]
Have you tested the launch notification? As you probably know, Lutris v.0.4.15 is now live and it solves the issue of the GUI displaying. I think this can be merged into master if it works as intended. I’ll package up the new release for the Kodi repo.

**Comment by RobLoach** [comment]
Sweet! I'll merge it. It's good to give feedback either way. Yay for new Lutris!
