### ISSUE TITLE
Can't find Lutris executable even though it's specified

### ISSUE THREAD

**Issue by billywade** [RobLoach/lutris-kodi-addon#34]
Using the latest from the repo, every time I try to launch it says "executable not found," even though I'm pointing it to /usr/bin/lutris.

**Comment by RobLoach** [comment]
Thanks for giving this a try! Does it say "Lutris Not Found"?

It happens when you select "Launch Lutris?

Could be happening around this part:
https://github.com/RobLoach/lutris-kodi-addon/blob/master/default.py#L32-L37

Is Use Custom Path enabled?

**Comment by billywade** [comment]
Thank you for the quick reply! It's my favorite launcher for desktop games, so your ten foot UI through Kodi is icing on the cake. 

So, in order: 
It does say "Lutris Not Found".
It happens when I select "Launch Lutris".
It happens both when "Use Custom Path" is enabled and when it's disabled.

Are there any logs you need?

**Comment by billywade** [comment]
EDIT: The problem was on my end. My distro's stable build of Lutris had a bug, so I built from the git and it runs fine now.

**Comment by RobLoach** [comment]
Which distro are you on? Was there something wrong with the package?

**Comment by billywade** [comment]
Manjaro, so Arch, just a bit behind. When run from the terminal, it complains of a reference to Lutris, when the reference should have been to lutris. Just a typo in the code that's since been fixed in the development branch.
