### ISSUE TITLE
Addon does not prevent suspend or shutdown depending on Kodi settings

### ISSUE THREAD

**Issue by arustler** [RobLoach/lutris-kodi-addon#36]
When starting a game Kodi will suspend or shutdown depending on the Kodi settings.
It seems that the runner does not matter. It happens to Wine and Retroarch so far. I don't have any other runners currently installed.

My setup:

- Intel NUC5i5RYH with Xbox One S Controller
- Ubuntu 18.05 Server Install
- openbox WM

Boot process:

1. autologin via getty@tty1.service
2. starting openbox-session via .xinitrc
3. starting /usr/bin/kodi -fs via .conf/openbox/autostart

I am trying to avoid the installation of a Power Managing Tool like pm-utils. I'd like to configure the Power Management options via Kodi.

I have tried to figure out how Kodi executes the suspend/shutdown signal but was unsuccessful. The Python Kodi API does only give the option to toggle the DPMS option.

I'm willing to help in this matter and provide needed logs.

**Comment by arustler** [comment]
Found a Solution:
Basically use the JsonRPC API to set the powermanagement values
Created a pull request #37

**Comment by RobLoach** [comment]
Smart! Thanks so much.

**Comment by arustler** [comment]
Issue closed, pull request #37 merged to master. Thanks @RobLoach
