### ISSUE TITLE
Add "Runner" Filter

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/lutris-kodi-addon#4]
Allow filtering and sorting of the game's Runner.

**Comment by solbero** [comment]
Shouldn’t this issue have been closed with https://github.com/RobLoach/lutris-kodi-addon/commit/90e6e5bd3832d0cabc25c98324657e4b6942bbbc

**Comment by RobLoach** [comment]
Hmm, I think this is more about being able to filter the listing by Runner or Platform.

Like, open Kodi's sidebar and be able to show games by certain runners.

**Comment by RobLoach** [comment]
Similar to how you can filter Movie genres.

**Comment by solbero** [comment]
Ahh, right. I completely misunderstood then.
