### ISSUE TITLE
Show game cover instead of game icon

### ISSUE THREAD

**Issue by trymeouteh** [RobLoach/lutris-kodi-addon#50]
Personally I think the games pictures should be the covers and not the icons. Please consider having a setting to change this or to change the game images in Kodi to the Lutris game covers.

**Comment by solbero** [comment]
Lutris does not provide a lot of artwork for the games. It provides a low-res icon and a low-res banner. Per now, there does not exist a game artwork scraper for Kodi and I do not have plans to write one myself.

I have assigned the icon to the Kodi artwork type `icon` and the banner to `banner` and `thumbnail`. This is as close it is possible today to match the artwork provided by Lutris to the artwork dimensions expected by Kodi.

However, it seems like there are plans for Lutris to move to more high-res artwork and adding cover artwork to games. When that happens I will update the add-on.

**Comment by RobLoach** [comment]
Thanks! Once Lutris gets the higher res images we can switch to them.

**Comment by trymeouteh** [comment]
I do add my game manually into Lutris and therefore I add custom artwork, I even replace the artwork in the Lutris icons folder to increase the file size.

To have a setting to switch between icons and covers would be nice even if it is set to icons by default.

**Comment by solbero** [comment]
Commit https://github.com/RobLoach/lutris-kodi-addon/commit/337c425292775a5e63aafec213e74ec1d4902031 adds a toggle in the add-on settings to prefer covers over icons. You can [download the latest .zip](https://github.com/RobLoach/lutris-kodi-addon/archive/develop.zip) of the `develop` branch to test it. The add-on from the `develop` branch is only compatible with Kodi v19 Matrix.
