### ISSUE TITLE
Outdated addon in the repository

### ISSUE THREAD

**Issue by mYnDstrEAm** [RobLoach/lutris-kodi-addon#54]
I used [this version](https://github.com/RobLoach/lutris-kodi-addon/issues/46#issuecomment-754934779) on Debian10/KDE. Apparently it recently it stopped working with this error in the logs:

```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'result' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/home/username/.kodi/addons/plugin.lutris/addon.py", line 7, in <module>
                                                       from lib import main
                                                     File "/home/username/.kodi/addons/plugin.lutris/lib/main.py", line 23, in <module>
                                                       game_list = lutris.check_cache('games', lutris.get_games)
                                                     File "/home/username/.kodi/addons/plugin.lutris/lib/lutris.py", line 177, in check_cache
                                                       array = rebuild_cache(endpoint, func, *args, **kwargs)
                                                     File "/home/username/.kodi/addons/plugin.lutris/lib/lutris.py", line 197, in rebuild_cache
                                                       array = func(*args, **kwargs)
                                                     File "/home/username/.kodi/addons/plugin.lutris/lib/lutris.py", line 116, in get_games
                                                       response = json.loads(result)
                                                   UnboundLocalError: local variable 'result' referenced before assignment
                                                   -->End of Python script error report<--
```

So I deinstalled the addon (by going to Games -> Lutris -> pressing C -> Information -> Deinstall) and tried reinstalling it from the solbero's repository. However, it's still version 1.4.3 there. Could a newer (and functional on Debian) version be uploaded to the repo?

**Comment by solbero** [comment]
There are now to unofficial repositories for the add-on. The respository you tried to use is for Leia and below. Since Kodi Matrix switched to Python 3 you need to use the new Matrix repository: https://github.com/solbero/repository.solbero.matrix/blob/master/README.md

**Comment by solbero** [comment]
Otherwise, it seems to be a problem with the caching function. The caching implementation is rewritten in the development branch, but I haven't made a release yet.

My laptop is being repaired, but I'll do a new release with the new implementation when I get it back.

**Comment by solbero** [comment]
I have updated the add-on in my unofficial Matrix repository. Please report back if this update fixed your issues.

**Comment by mYnDstrEAm** [comment]
It has not because I can't install that repository: it says file content has the wrong structure. In the logs it only says `ERROR <general>: GetDirectory - Error getting zip://[...]repository.solbero.matrix-1.0.0.zip/`

**Comment by solbero** [comment]
Ok, that is not great. I just tested the Matrix repository in a virtual machine and it installed without a problem. The machine is running Ubuntu 20.04.

However, Kodi caches add-on packages, so lets try a complete reinstall.
1. Uninstall the add-on and the repository in Kodi.
2. Then navigate in a file browser to `~/.kodi/addons/` and delete any folders called `script.lutris` or `plugin.lutris`.
3. Do the same for `~/.kodi/userdata/addon_data/`.
4. Also make sure that any .zip-files relating to the add-on, such  `script.lutris`, `plugin.lutris` or `repository.solbero` are deleted from `~/.kodi/addons/packages/`.

Then download the [onofficial repository](https://github.com/solbero/repository.solbero.matrix/raw/master/repository.solbero.matrix/repository.solbero.matrix.zip) again and install it.

**Comment by solbero** [comment]
The md5 hash of the repository .zip-file should be `
87779223a8069e37f95ade007142d7c3`.

**Comment by mYnDstrEAm** [comment]
I deleted a few solbero repository files from those directories (no lutris addon files) then I installed that .zip file you linked (md5sum matches and sha256sum is `226f43821220511ae0809aac080a0ddbf84e7e0adb37da90f175ca13ea22c2b6`) even though I'm not sure why it's not the .zip file on the github page which is what I tried earlier. The repository installed fine but when I searched for Lutris Kodi just quit. I restarted it and now get these errors in the logs when I try to open the repository:

```
ERROR <general>: Open - <https://raw.githubusercontent.com/solbero/repository.solbero.matrix/master/addons.xml.md5> failed to open
ERROR <general>: CRepository: failed read 'https://raw.githubusercontent.com/solbero/repository.solbero.matrix/master/addons.xml.md5'
WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
ERROR <general>: GetDirectory - Error getting addons://repository.solbero.matrix/
ERROR <general>: CGUIMediaWindow::GetDirectory(addons://repository.solbero.matrix/) failed
```

**Comment by solbero** [comment]
That last error is not related to the add-on, but with Lutris. The add-on tries to fetch the games list from Lutris, but the comand fails: `Command '['/usr/games/lutris', '--list-games', '--installed', '--json']' returned non-zero exit status 1.`

From the debug log you posted from Lutris, it looks like the magic library fails. This there is a commit https://github.com/lutris/lutris/commit/b1a6129258624317d21d7e97e7db6e683c0b5da7 recently related to some bugs with this library. Make sure `python-magic` is installed on your system. Might also be worth trying to run Lutris from source.

**Comment by mYnDstrEAm** [comment]
They're installed and should be the right version:
```
dpkg -s lutris | grep -i version
Version: 0.5.8.4
dpkg -s python-magic | grep -i version
Version: 2:0.4.15-2
```
But I guess that's not a problem of the repo so I'll ask elsewhere if I can't solve it so this issue can be closed. Thank you!
