### ISSUE TITLE
Addon not detecting all games

### ISSUE THREAD

**Issue by jacobhallberg98** [RobLoach/lutris-kodi-addon#57]
Hello!

When I launch the Lutris addon in Kodi it only detects two of my games, but as you can see in the attached screenshots I have a lot more than just those two. Why isn't it detecting all of them?
![2021-08-08-155012_1920x1080_scrot](https://user-images.githubusercontent.com/69006684/128634255-9d5c0c19-7f2e-44af-8eab-a131be7421d7.png)
![2021-08-08-154956_1920x1080_scrot](https://user-images.githubusercontent.com/69006684/128634260-ff0c200b-b1ea-4e15-b91c-e9dc71bfc6a5.png)

**Comment by solbero** [comment]
The add-on caches the games list from lutris for 6 hours when you first start it. If you started the add-on with only those two games and installed the rest afterwards, it would not show the rest.

You can delete the cache in the add-on setting to force a refresh.

**Comment by jacobhallberg98** [comment]
I deleted the cache and that solved the issue, thanks!
