### ISSUE TITLE
Only icons are shown instead of covers / restricted view type selection 

### ISSUE THREAD

**Issue by Juppstein** [RobLoach/lutris-kodi-addon#62]
Despite me having set the option to prefer covers Kodi shows only icons. 
Also the selection of views is restricted to list and preview, although the skin recognizes  the addon as a game addon and according to the skin I should have at least 4 views available for game addons. Just to test it out I modded the skin config to add more views, but this is not recognized by the Lutris addon. 

Here's a log in debug mode:  https://paste.ubuntu.com/p/3RVZKVjhMq/

**Comment by solbero** [comment]
This project has been a bit on the back-burner for the past year, but hopefully I'll get the time soon to resole your issue.

**Comment by Juppstein** [comment]
I guess this addon is dead now?

**Comment by solbero** [comment]
Yes, it is.
